name = "okonomia-skraning"
type = "javascript"
account_id = "342285476fa519e04a9db74787b46103"

workers_dev = true
route = ""
zone_id = ""

[build]
command = "yarn build"          ## --build-command
watch_dir = "src"               ## --build-watch-path


[build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
kv_persist = true # Defaults to ./.mf/

# [secrets]
# PASSBOOK_CERT
# PASSBOOK_PRIVATE_KEY


[env.staging]
workers_dev = true
name = "okonomia-staging"
vars = { ENVIRONMENT = "staging" }
# routes = ["dev.ok.slodi.is/api/*"]
kv_namespaces = [
  { binding = "USERS", id = "50128b9acd284fd0befc35f4f708df54" },
  { binding = "ASSETS", id = "8b5a1638924440e586e673da9f8d0e1d" },
  { binding = "BUCKET", id = "b4316205bd67496a8343eea5b96d893a" },
]

[env.staging.durable_objects]
bindings = [{name = "USER_WATCHER", class_name = "UserWatcher"}]


[env.production]
workers_dev = false
name = "okonomia-prod"
vars = { ENVIRONMENT = "production" }
zone_id = "7e2f351670c0d0ea67d2bb8737ec88a1"
routes = [
  "okonomia.club/api*",
]
kv_namespaces = [
  { binding = "USERS", id = "28a4069c157b4cbfa8299885e7bd3806" },
  { binding = "ASSETS", id = "381c57fad1224e028b4ed7e907d30bbd" },
  { binding = "BUCKET", id = "7717c4835de148dd8b707476a8acb4e9" },
]

[env.production.durable_objects]
bindings = [{name = "USER_WATCHER", class_name = "UserWatcher"}]