name = "okonomia-skraning"
type = "javascript"
account_id = "342285476fa519e04a9db74787b46103"

workers_dev = true
route = ""
zone_id = ""

[build]
command = "yarn build"          ## --build-command
watch_dir = "src"               ## --build-watch-path


[build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
kv_persist = true # Defaults to ./.mf/


[env.staging]
name = "okonomia-staging"
vars = { ENVIRONMENT = "staging" }
route = "dev.ok.slodi.is/api/*"
kv_namespaces = [
  { binding = "USERS", id = "50128b9acd284fd0befc35f4f708df54" },
]

[env.production]
name = "okonomia-prod"
vars = { ENVIRONMENT = "production" }
routes = [
  "ok.slodi.is/api/*",
]
kv_namespaces = [
  { binding = "USERS", id = "28a4069c157b4cbfa8299885e7bd3806" },
]
